name: deploy

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        name: CD Pipeline
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: build react
              run: npm run build

            - name: Get current time
              uses: 1466587594/get-current-time@v2
              id: current-time
              with:
                format: YYYY-MM-DDTHH-mm-ss # 다른 포맷으로 변경 가능(MomentJS format syntax)
                utcOffset: "+09:00" # 한국 시간에 맞추기 위함


            - name: Generate deployment package
              run: |
                mkdir -p deploy
                cp -r ./build deploy/build
                cp -r ./.platform deploy/
                cp Procfile deploy/Procfile
                
                zip -r deploy.zip ./deploy

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: ${{ secrets.CLIENT_APPLICATION_NAME }}
                  environment_name: ${{ secrets.CLIENT_ENVIRONMENT_NAME }}
                  region: ap-northeast-2
                  version_label: Github Action-${{steps.current-time.outputs.formattedTime}} # 배포 버전은 타임스탬프를 이용하여 구분
                  deployment_package: deploy.zip
                  wait_for_environment_recovery: 120