name: Deploy

 

# Controls when the action will run. Triggers the workflow on push or pull request

# events but only for the master branch

on:

  push:
    branches: [main]

  pull_request:
    branches: [main]

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install

 

      - name: Gnerate Bundle File
        run: npm run build

      - name: check dir
        run: cd build && ls -al

      - name: Generate deployment package
        run: cd build && zip -r deploy.zip .

      - name: Deploy to EB

        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.CLIENT_APPLICATION_NAME }}
          environment_name: ${{ secrets.CLIENT_ENVIRONMENT_NAME }}
          version_label: ${{github.run_number}}
          use_existing_version_if_available: true
          region: ap-northeast-2
          deployment_package: build/deploy.zip